name: Check desktop file
"on":
  pull_request:
    branches: ["master"]
    paths:
      - .github/workflows/validate-desktop-file.yml
      - Source/LoadByOS/LinuxConfigApp/Libation.desktop
  push:
    branches: ["master"]
    paths:
      - .github/workflows/validate-desktop-file.yml
      - Source/LoadByOS/LinuxConfigApp/Libation.desktop

jobs:
  validate-desktop-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt --yes install desktop-file-utils
      - name: Check the desktop file
        run: desktop-file-validate Source/LoadByOS/LinuxConfigApp/Libation.desktop
