name: Validate MetaInfo
"on":
  pull_request:
    branches: ["master"]
    paths:
      - .github/workflows/validate-appstream-metainfo.yml
      - Source/LoadByOS/LinuxConfigApp/com.getlibation.Libation.metainfo.xml
  push:
    branches: ["master"]
    paths:
      - .github/workflows/validate-appstream-metainfo.yml
      - Source/LoadByOS/LinuxConfigApp/com.getlibation.Libation.metainfo.xml

jobs:
  validate-appstream-metainfo:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub/flatpak-builder-lint:latest
    steps:
      - uses: actions/checkout@v4
      - name: Check the MetaInfo file
        run: flatpak-builder-lint appstream Source/LoadByOS/LinuxConfigApp/com.getlibation.Libation.metainfo.xml
